#MoBoxFrp 主控配置文件
#By MossCG

#----------------------------------
#邮箱模块信息

#邮箱开启设置
enableMail: false
#邮箱账号密码
mailAccount: aaa@163.com
mailPassword: 123456
#邮箱SMTP地址端口
mailSMTPHost: smtp.mossfrp.nb
mailSMTPPort: 465
#验证码可用时长（分钟）
mailCodeTime: 5

#----------------------------------
#短信模块信息

#短信验证码功能
#基于阿里云SMS
enableSMS: false
#阿里云AccessKey信息
AliyunAccessKeyID: "123"
AliyunAccessKeySecret: "456"
#短信信息
SMSSignName: "墨盒软件"
SMSTemplateCode: "SMS_123456789"
#短信冷却（秒）
SMSCoolDown: 60
#验证码可用时长（分钟）
SMSCodeTime: 5

#----------------------------------
#数据库设置

#是否启用MySQL（不启用则为SQLite存储数据）
#切换前请做好数据备份（或一开始就选好）
#贸然切换可能导致数据丢失
enableMySQL: false
#MySQL设置（SQLite不用管这个）
databaseAddress: "127.0.0.1"
databasePort: "3306"
databaseDatabase: "moboxfrp"
databaseUser: "root"
databasePassword: "123456"
#连接池大小（一般情况下3够用了）
databasePoolSize: 3
#数据库连接检查冷却（60s可供参考，太短会降低响应速度）
databaseCheckCD: 60
#数据库连接刷新冷却（300s可供参考，意味着每隔对应时长重新连接一次到数据库）
databaseRefreshCD: 300
#----------------------------------

