#MoBoxFrp 主控配置文件


#----------------------------------
#邮箱模块信息

#邮箱开启设置
enableMail: false
#邮箱账号密码
mailAccount: aaa@163.com
mailPassword: 123456
#邮箱SMTP地址端口
mailSMTPHost: smtp.mossfrp.nb
mailSMTPPort: 465
#验证码可用时长（分钟）
mailCodeTime: 5

#----------------------------------
#短信模块信息

#短信验证码功能
#基于阿里云SMS
enableSMS: false
#阿里云AccessKey信息
AliyunAccessKeyID: "123"
AliyunAccessKeySecret: "456"
#短信信息
SMSSignName: "墨盒软件"
SMSTemplateCode: "SMS_123456789"
#短信冷却（秒）
SMSCoolDown: 60
#验证码可用时长（分钟）
SMSCodeTime: 5

#----------------------------------

